/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hillary
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ChooseCharacter extends javax.swing.JFrame {

    /**
     * Creates new form ChooseCharacter
     */
    public ChooseCharacter() {
        initComponents();
        
        
        btnEzekiel.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openStoryLineForCharacter("Ezekiel");
            }
        });
        btnEarl.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openStoryLineForCharacter("Earl");
            }
        });
        btnJivonz.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openStoryLineForCharacter("Jivonz");
            }
        });
        btnShaina.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openStoryLineForCharacter("Shaina");
            }
        });
        
        btnRichelle.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                openStoryLineForCharacter("Richelle");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void openStoryLineForCharacter(String characterName) {
        StoryLine storyLine = new StoryLine(characterName);
        storyLine.setVisible(true);
        this.dispose(); // Close the current GUI
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtChooseChar = new javax.swing.JTextField();
        lblEzekiel = new javax.swing.JLabel();
        lblJivonz = new javax.swing.JLabel();
        lblEarl = new javax.swing.JLabel();
        lblShaina = new javax.swing.JLabel();
        lblRichelle = new javax.swing.JLabel();
        btnEzekiel = new javax.swing.JButton();
        btnEarl = new javax.swing.JButton();
        btnJivonz = new javax.swing.JButton();
        btnShaina = new javax.swing.JButton();
        btnRichelle = new javax.swing.JButton();
        lblBackgroundChar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtChooseChar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtChooseChar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChooseChar.setText("CHOOSE A CHARACTER");
        getContentPane().add(txtChooseChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 340, 60));

        lblEzekiel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblEzekiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 260, 240));

        lblJivonz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblJivonz, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 270, 230));

        lblEarl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblEarl, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 260, 230));

        lblShaina.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblShaina, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 290, 250));

        lblRichelle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblRichelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 280, 250));

        btnEzekiel.setText("EZEKIEL");
        btnEzekiel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEzekielActionPerformed(evt);
            }
        });
        getContentPane().add(btnEzekiel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 130, 30));

        btnEarl.setText("EARL");
        btnEarl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEarlActionPerformed(evt);
            }
        });
        getContentPane().add(btnEarl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, 150, 30));

        btnJivonz.setText("JIVONZ");
        btnJivonz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJivonzActionPerformed(evt);
            }
        });
        getContentPane().add(btnJivonz, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 150, 30));

        btnShaina.setText("SHAINA");
        btnShaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShainaActionPerformed(evt);
            }
        });
        getContentPane().add(btnShaina, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 760, 140, 30));

        btnRichelle.setText("RICHELLE");
        btnRichelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRichelleActionPerformed(evt);
            }
        });
        getContentPane().add(btnRichelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 760, 140, 30));

        lblBackgroundChar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/zombiebg (1).png"))); // NOI18N
        getContentPane().add(lblBackgroundChar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEzekielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEzekielActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEzekielActionPerformed

    private void btnJivonzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJivonzActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJivonzActionPerformed

    private void btnEarlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEarlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEarlActionPerformed

    private void btnShainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShainaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShainaActionPerformed

    private void btnRichelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRichelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRichelleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCharacter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCharacter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEarl;
    private javax.swing.JButton btnEzekiel;
    private javax.swing.JButton btnJivonz;
    private javax.swing.JButton btnRichelle;
    private javax.swing.JButton btnShaina;
    private javax.swing.JLabel lblBackgroundChar;
    private javax.swing.JLabel lblEarl;
    private javax.swing.JLabel lblEzekiel;
    private javax.swing.JLabel lblJivonz;
    private javax.swing.JLabel lblRichelle;
    private javax.swing.JLabel lblShaina;
    private javax.swing.JTextField txtChooseChar;
    // End of variables declaration//GEN-END:variables
}
