/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hillary
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class Store extends javax.swing.JFrame {
    private Inventory inventory;
    /**
     * Creates new form Store
     * @param inventory
     */
    public Store(Inventory inventory) {
        this.inventory = inventory;
        initComponents();
    }

      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblCard1 = new javax.swing.JLabel();
        lblCard2 = new javax.swing.JLabel();
        lblCard3 = new javax.swing.JLabel();
        lblBorder = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        lblArrow2 = new javax.swing.JLabel();
        lblArrow1 = new javax.swing.JLabel();
        btnMenu = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        lblAvatar = new javax.swing.JLabel();
        lblMessageBox = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        jLabel2.setText("Welcome to Dota 3 Store");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/scissor.png"))); // NOI18N
        lblCard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 210, -1));

        lblCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/scissor.png"))); // NOI18N
        lblCard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 210, 260));

        lblCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/scissor.png"))); // NOI18N
        lblCard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(lblCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 220, 260));

        lblBorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Untitled_design_6.png"))); // NOI18N
        lblBorder.setText("jLabel5");
        jPanel1.add(lblBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 900, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 960, 570));

        btnNext.setBackground(new java.awt.Color(255, 204, 51));
        btnNext.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnNext.setText("NEXT");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 660, 120, 40));
        btnNext.getAccessibleContext().setAccessibleParent(jPanel1);

        btnPrevious.setBackground(new java.awt.Color(255, 204, 51));
        btnPrevious.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 660, 120, 40));

        btnPurchase.setBackground(new java.awt.Color(255, 204, 51));
        btnPurchase.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        btnPurchase.setText("PURCHASE");
        btnPurchase.setToolTipText("");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });
        getContentPane().add(btnPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, -1, 40));
        btnPurchase.getAccessibleContext().setAccessibleParent(jPanel1);

        lblArrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/New Piskel (12).gif"))); // NOI18N
        getContentPane().add(lblArrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 130, 70));

        lblArrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/New Piskel (12).gif"))); // NOI18N
        getContentPane().add(lblArrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 560, 130, 70));

        btnMenu.setBackground(new java.awt.Color(255, 204, 51));
        btnMenu.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        btnMenu.setText("MAIN MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 650, 130, 60));

        btnInventory.setBackground(new java.awt.Color(255, 204, 51));
        btnInventory.setFont(new java.awt.Font("Baskerville Old Face", 1, 12)); // NOI18N
        btnInventory.setText("INVENTORY");
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 130, 60));

        lblWelcome.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblWelcome.setText("Welcome to the secret shop");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 220, 30));

        lblAvatar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/character.gif"))); // NOI18N
        lblAvatar.setText("jLabel1");
        getContentPane().add(lblAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 240, 270));

        lblMessageBox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/dialogue1.gif"))); // NOI18N
        getContentPane().add(lblMessageBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 620, 380));

        lblBackground.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/store.jpg"))); // NOI18N
        lblBackground.setToolTipText("");
        lblBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1460, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        // TODO add your handling code here:
        Inventory inventory = new Inventory();
        inventory.show();
        dispose(); 
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu = new Menu();
        menu.show();
        dispose();
        
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Inventory inventory = new Inventory();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Store(inventory).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblArrow1;
    private javax.swing.JLabel lblArrow2;
    private javax.swing.JLabel lblAvatar;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBorder;
    private javax.swing.JLabel lblCard1;
    private javax.swing.JLabel lblCard2;
    private javax.swing.JLabel lblCard3;
    private javax.swing.JLabel lblMessageBox;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
